/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "grid-cols-1",
    "grid-cols-2",
    "grid-cols-4",
    "md:grid-cols-1",
    "md:grid-cols-2",
    "md:grid-cols-4",
    "lg:grid-cols-1",
    "lg:grid-cols-2",
    "lg:grid-cols-4",
    "items-center",
    "items-start",
    "items-end",
    "justify-center",
    "justify-start",
    "justify-end",
    "justify-between",
    "justify-around",
    "flex-row",
    "flex-col",
    "gap-2",
    "gap-4",
    "gap-8",
    "gap-14",
    "gap-10",
    "text-center",
    "decoration-primary",
    "underline",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
